Adding ResInsight

diff --git a/.github/workflows/ci_brew_opm-flow_resinsight_macos.yml b/.github/workflows/ci_brew_opm-flow_resinsight_macos.yml
--- a/.github/workflows/ci_brew_opm-flow_resinsight_macos.yml
+++ b/.github/workflows/ci_brew_opm-flow_resinsight_macos.yml
@@ -1,4 +1,4 @@
-name: Install OPM Flow in macOS using brew
+name: Install OPM Flow and ResInsight in macOS using brew
 
 on:
  push:
@@ -8,7 +8,7 @@ on:
    
 jobs:
   run-pycopm-local:
-    timeout-minutes: 60
+    timeout-minutes: 120
     strategy:
       fail-fast: false
       matrix:
@@ -26,6 +26,20 @@ jobs:
       uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python-version }}
+
+    - name: Install ResInsight
+      run: |
+        brew install cssr-tools/opm/resinsight
+
+    - name: Check if ResInsight succeeded
+      run: |
+        file="/opt/homebrew/Cellar/resinsight/2025.12.0/ResInsight.app"
+        if [[ -f "$file" ]]; then
+          echo "The installation of ResInsight succeeded"
+        else
+          echo "The installation of ResInsight failed"
+          exit 1
+        fi
     
     - name: Install OPM Flow
       run: |
